const sidebar = {
    algorithmPracticeSidebar: [
        'README',
        {
            label: '剑指 offer',
            type: 'autogenerated',
            dirName: 'codingInterviews',
        },
        {
            label: 'leetcode',
            type: 'autogenerated',
            dirName: 'leetcode',
        },
    ]


};

module.exports = sidebar;